version: '3.8'

services:
  vite-dev:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:5173"
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
